export const environment = {
  production: false,
  userApiUrl: 'http://localhost:8086/api/user',
  courseApiUrl: 'http://localhost:8083/api/course',
  courseMaterialApiUrl: 'http://localhost:8083/api/course-material',
  topicApiUrl: 'http://localhost:8083/api/topic',
  lessonApiUrl: 'http://localhost:8083/api/lesson',
  examApiUrl: 'http://localhost:8085/api/exam',
  assignmentApiUrl: 'http://localhost:8085/api/assignment',
  examSolutionApiUrl: 'http://localhost:8085/api/exam-solution',
  assignmentSolutionApiUrl: 'http://localhost:8085/api/assignment-solution',
  feedbackApiUrl: 'http://localhost:8081/api/feedback',
  faqApiUrl: 'http://localhost:8082/api/faq',
  jwtSecret: 'AAUonLineLEArning',
};
